### ISSUE TITLE
SPI RECV can not get data

### ISSUE THREAD

**Issue by ygd2013520** [kjarvel/hifive1revb_wifi#2]
hi, thank you very much for your code, I can use this code to connect my ap, but the spi_recv can not get the response. For example, "AT+RST" cmd send can get response "OK",but I use the spi_recv can not get anything?

**Comment by kjarvel** [comment]
Hi,

Try with a simple command such as "AT" only. It should normally get a response "OK", but if there are queued replies, they will also be read out. The ESP32 will not send any reply unless you send in an AT command to it. So you cannot simply call "spi_recv" without first sending in a command to the ESP32 using "spi_send", see the example at the end of main.c.

**Comment by ygd2013520** [comment]
Thanks for your reply,
I see the example at the end of main.c, I was trying input one cmd, but the "spi_recv" can not get anything. Like this  : I input "AT+RST" cmd and I printf the "recv_str" ,nothing with it
| Waiting for handshake pin ready...DONE
* Optional: Enter AT commands (see "ESP32 AT Instruction Set and Examples")
* Enter AT command: 
[+] spi_send: AT+RST
 | spi_xfer_recv_header: sending: 02 00 00 00
 | Waiting for handshake pin ready...DONE
 | spi_send length: sending: (8) 08 00 00 41
 | Waiting for handshake pin ready...DONE
 | spi_send data: sending:
 41 54 2b 52 53 54 0d 0a
 | Waiting for handshake pin ready...DONE
[+] spi_xfer_send_header: sending: 01 00 00 00
 | Waiting for handshake pin ready...DONE
 | spi_recv length: 9, B
 | Waiting for handshake pin ready...DONE
 | -- ESP32 ----> 
recv_str = 
* Enter AT command: 

I want to get response for every cmd, so I know the cmd is fail or success. Thanks very much.

**Comment by ygd2013520** [comment]
Thanks for your reply,
I see the example at the end of main.c, I was trying input one cmd, but the "spi_recv" can not get anything. Like this  : I input "AT+RST" cmd and I printf the "recv_str" ,nothing with it
| Waiting for handshake pin ready...DONE
* Optional: Enter AT commands (see "ESP32 AT Instruction Set and Examples")
* Enter AT command: 
[+] spi_send: AT+RST
 | spi_xfer_recv_header: sending: 02 00 00 00
 | Waiting for handshake pin ready...DONE
 | spi_send length: sending: (8) 08 00 00 41
 | Waiting for handshake pin ready...DONE
 | spi_send data: sending:
 41 54 2b 52 53 54 0d 0a
 | Waiting for handshake pin ready...DONE
[+] spi_xfer_send_header: sending: 01 00 00 00
 | Waiting for handshake pin ready...DONE
 | spi_recv length: 9, B
 | Waiting for handshake pin ready...DONE
 | -- ESP32 ----> 
recv_str = 
* Enter AT command: 

I want to get response for every cmd, so I know the cmd is fail or success. Thanks very much.

**Comment by kjarvel** [comment]
OK, did you try with the latest update of the code? That is the v1.2 version:
https://github.com/kjarvel/hifive1revb_wifi/releases

It prints out the response for every AT command.
I would recommend that you try with "AT" instead of "AT+RST" since "AT+RST" resets the ESP32 module that you are trying to talk to (it works, but it's more complicated).

Thanks!
