### ISSUE TITLE
why is the CPU 320MHz

### ISSUE THREAD

**Issue by luott7421** [kjarvel/hifive1revb_wifi#3]
In len 44 of cpu,c

**Comment by kjarvel** [comment]
Hi luott7421,

That is a very short and interesting question.
In the `cpu_clock_init` function in cpu.c, the clock speed is set to 320 Mhz.

* Why?
Only to show an example on how to do it. It is not required for the WiFi demo. 

* How?
I hope the comments on line 41-45 explains it all.
https://github.com/kjarvel/hifive1revb_wifi/blob/v1.4/cpu.c#L41
The clocks are configured according to **Chapter 6.1 Clock Generation Overview** in the Freedom E310-G002 Manual: https://www.sifive.com/boards/hifive1-rev-b
