### ISSUE TITLE
Accessing Hifi RevB to access wifi

### ISSUE THREAD

**Issue by abhi-84** [kjarvel/hifive1revb_wifi#4]
How to fetch sensor value using HiFive Rev B board and hand it to ESP32 to send via wifi?

**Comment by kjarvel** [comment]
Here is some documentation of this project: https://github.com/kjarvel/hifive1revb_wifi/wiki/HiFive1-Rev-B-WiFi-and-BLE
Source code and readme available here: https://github.com/kjarvel/hifive1revb_wifi
Good luck!
